version: "3.9"

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
    name: ping_app_network