services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_USER_DB_PASSWORD}
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_USER_DB_PORT}:${POSTGRES_USER_DB_DOCKER_PORT}"
    networks:
      - shared-network
    command:
      - "postgres"
      - "-c"
      - "port=${POSTGRES_USER_DB_PORT}"
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      POSTGRES_DB_URL: ${POSTGRES_DB_DOCKER_URL}
      POSTGRES_USER_DB_USERNAME: ${POSTGRES_USER_DB_USERNAME}
      POSTGRES_USER_DB_PASSWORD: ${POSTGRES_USER_DB_PASSWORD}
      POSTGRES_USER_DB_NAME: ${POSTGRES_USER_DB_NAME}
      POSTGRES_USER_DB_PORT: ${POSTGRES_USER_DB_PORT}
      POSTGRES_USER_DB_DOCKER_PORT: ${POSTGRES_USER_DB_DOCKER_PORT}
    depends_on:
      - postgres
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_DOCKER_PORT}"
    networks:
      - shared-network
volumes:
  postgres_user_data:

networks:
  shared-network:
    external: false
    name: ping_app_network