services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_DOCKER_PORT}"
    networks:
      - app-network
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB_URL: ${POSTGRES_DB_URL}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB_DOCKER_PORT: ${POSTGRES_DB_DOCKER_PORT}
    depends_on:
      - postgres
    ports:
      - "${BACKEND_PORT}:${BACKEND_DOCKER_PORT}"
    networks:
      - app-network
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge