services:
  db:
    image: postgres:15-alpine
    container_name: ${POSTGRES_HOST}
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - shared_network

  url_service_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-service-app
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${SPRING_APP_PORT}:8080"
    depends_on:
      - db
    networks:
      - shared_network

volumes:
  postgres_data:

networks:
  shared_network:
    external: false
    name: ping_app_network